In [1]:
import numpy as np
np.__version__

'1.16.2'

In [2]:
import pandas as pd
pd.__version__

'0.24.2'

## 1 Dimensional Array

It is similar to a list

In [5]:
my_list = [11,12,13,14,15]

In [6]:
my_list

[11, 12, 13, 14, 15]

In [7]:
_1D = np.array(my_list)

In [8]:
_1D

array([11, 12, 13, 14, 15])

## 2 Dimensional Array

In [10]:
my_list_2 = [[1,2,3],[4,5,6],[7,8,9]]
my_list_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
_2D = np.array(my_list_2)
_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Generate random numbers

In [13]:
for numbers in range(0,11):
    print(numbers)

0
1
2
3
4
5
6
7
8
9
10


In [14]:
np.arange(0,101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
np.ones((5,5)) * 15

array([[15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.]])

In [41]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [39]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
np.random.rand(2)

array([0.13555314, 0.21515604])

In [43]:
np.random.rand(100)

array([4.97836792e-01, 3.27462789e-01, 9.83521602e-01, 1.78971723e-01,
       6.95210710e-01, 5.50311989e-02, 2.68590010e-01, 8.51053747e-01,
       4.18839790e-01, 7.91300220e-03, 1.32748866e-01, 2.41417972e-01,
       5.16485025e-01, 3.52352544e-01, 2.30843018e-01, 4.64355765e-01,
       7.06946733e-01, 7.64741977e-01, 8.10149747e-01, 6.39527599e-01,
       3.41918148e-01, 3.59959680e-01, 5.33390585e-01, 1.55665231e-01,
       2.05067120e-01, 7.04605711e-01, 7.72694028e-01, 1.27227539e-01,
       3.16540765e-01, 6.25715795e-01, 2.37346393e-01, 7.60352281e-01,
       7.08174145e-01, 5.80649214e-01, 8.08033822e-01, 1.58010329e-01,
       3.36868610e-01, 6.83596806e-01, 4.64015013e-01, 7.85028461e-01,
       6.39283620e-01, 7.37854035e-01, 8.22220439e-01, 4.72436029e-01,
       9.40180055e-01, 3.23917421e-01, 4.28947095e-01, 4.87213831e-01,
       5.09275072e-03, 9.70705998e-01, 2.65862165e-01, 7.38680202e-01,
       3.32710263e-01, 9.53622105e-01, 7.73156526e-01, 5.70688792e-01,
      

In [45]:
np.random.randint(0,500,30)

array([157, 126, 463,  38, 195, 387, 142, 373, 427, 249, 156, 180, 361,
       429, 431,  90, 408, 128, 467,  10, 329, 323, 114,   1, 157, 231,
        92, 298, 391, 250])

In [46]:
np.random.randint(0,50,10)

array([18, 20, 23, 31,  3,  0, 34, 21,  9, 19])

## Other operations

In [66]:
my_arr = np.random.randint(0,50,30)
my_arr

array([36, 18, 26,  1, 23, 18,  0, 48, 12, 30, 24,  6, 43, 18,  5, 26, 25,
       22, 40, 29, 27,  4, 44, 47, 14, 42, 45, 31, 24, 34])

In [67]:
my_arr.max()

48

In [68]:
np.max(my_arr)

48

In [69]:
my_arr.min()

0

In [70]:
np.min(my_arr)

0

In [71]:
my_arr.shape

(30,)

In [73]:
my_arr.reshape(10,3)

array([[36, 18, 26],
       [ 1, 23, 18],
       [ 0, 48, 12],
       [30, 24,  6],
       [43, 18,  5],
       [26, 25, 22],
       [40, 29, 27],
       [ 4, 44, 47],
       [14, 42, 45],
       [31, 24, 34]])

In [74]:
my_arr.dtype

dtype('int32')

## Arithmetic Operations

In [75]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Addition

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [78]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [81]:
arr[::2] + 50

array([50, 52, 54, 56, 58, 60])

## Subtraction

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

## Multiplication

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr * 12

array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120])

In [86]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [87]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

## Division

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr / arr

C:\Users\LENOVO\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [91]:
0/1

0.0

In [93]:
#1/0
#not possible

In [94]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

## Others

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Max

In [103]:
arr.max()

10

In [98]:
np.max(arr)

10

## Min

In [104]:
arr.min()

0

In [111]:
np.min(arr)

0

## Sin

In [99]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

## log

In [101]:
np.log(arr)

C:\Users\LENOVO\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

## exponent

In [102]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

## Slicing

In [105]:
_arr_1 = np.arange(11)

In [106]:
_arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
_arr_1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [110]:
_arr_1[0:10:2]

array([0, 2, 4, 6, 8])

In [112]:
_arr_2 = np.random.randint(0,11,20)
_arr_2

array([ 7,  8,  6,  8,  2,  3,  8,  0,  2,  3,  7,  1,  1,  1,  5, 10,  9,
        5,  5,  5])

In [113]:
_arr_3 = _arr_2.reshape(2,10)
_arr_3

array([[ 7,  8,  6,  8,  2,  3,  8,  0,  2,  3],
       [ 7,  1,  1,  1,  5, 10,  9,  5,  5,  5]])

In [114]:
_arr_3 = _arr_2.reshape(4,5)
_arr_3

array([[ 7,  8,  6,  8,  2],
       [ 3,  8,  0,  2,  3],
       [ 7,  1,  1,  1,  5],
       [10,  9,  5,  5,  5]])

In [115]:
_arr_3[1][2]

0

In [116]:
_arr_3[3][4]

5

In [117]:
_arr_3[-1][-1]

5

In [118]:
_arr_3[-4][-5]

7